### ISSUE TITLE
Renaming typoscript files breaks installation

### ISSUE THREAD

**Issue by spoonerWeb** [IchHabRecht/social_gdpr#13]
Hi Nicole,

please be aware changing the extension of the TypoScript files will break installations (new in version 3.2.0).
I'm importing the TypoScript in my site package via `@import 'EXT:social_gdpr/Configuration/TypoScript/setup.txt'.

With the change to `.typoscript` no YouTube videos are shown anymore.

Solution:
Add `constants.txt` and `setup.txt` (maybe a symlinks or copy) again until next breaking change release.

**Comment by IchHabRecht** [comment]
Hi @spoonerWeb,

Thank you for this remark. As the change was done back in April and the release was done back then I don't consider to take care about this change anymore. Sorry for your hickups.
